cart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from cart import views

# dev_15
app_name = "cart"

urlpatterns = [
    path("add/", views.add_cart, name="add_cart"),
    path("", views.summary_cart, name="summary_cart"),  # dev_18
    path("delete/", views.delete_cart, name="delete_cart"),  # dev_19
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls")),  # dev_1
    path("accounts/", include("accounts.urls")),  # dev_9
    path("cart/", include("cart.urls")),  # dev_15
]

# dev_2
# http://127.0.0.1:8000/media/파일경로
# MEDIA_URL = "media/"  # ex) /media/photo1.png
# MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# dev_2
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

# dev_8
app_name = "store"

# dev_1
urlpatterns = [
    path("", views.home, name="home"),
    path("about", views.about, name="about"),  # dev_8 어바웃 페이지 추가
    path("product/<int:product_id>", views.product, name="product"),  # dev_13 제품상세
    path(
        "category_summary", views.category_summary, name="category_summary"
    ),  # dev_14 카테고리 처리
    path(
        "category/<int:category_id>", views.category, name="category"
    ),  # dev_14 카테고리 처리
]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from cart.cart import Cart
from store.models import Product
from django.http import JsonResponse


# Create your views here.


# dev_15
def add_cart(request):
    cart = Cart(request)

    print("카트======", cart)

    if request.POST.get("action") == "post":

        # 상품 받아오기
        product_id = int(request.POST.get("product_id"))
        print("product_id", product_id)

        # 상품 개수
        product_qty = int(request.POST.get("product_qty"))
        print("product_qty", product_qty)

        # DB에서 찾아서 product 객체로 변환
        product = get_object_or_404(Product, id=product_id)

        # 세션에 저장
        cart.add(product, product_qty)

        # 카트 전체 개수 가져 오기
        cart_qty = cart.__len__()
        response = JsonResponse({"qty": cart_qty})

        # 세션확인 테스트
        cart.decrypt_all_sessions()

        return response


# dev_18
def summary_cart(request):

    # 카트객체 받아 오기
    cart = Cart(request)

    return render(request, "cart/summary.html", {"cart": cart})


# dev_19
def delete_cart(request):

    # 카트객체 받아 오기
    cart = Cart(request)

    if request.POST.get("action") == "post":
        product_id = int(request.POST.get("product_id"))

        product = Product.objects.get(id=product_id)

        cart.remove(product)

        return JsonResponse({"삭제_상품": product_id})

templates/cart/summary.html
<!--dev_18-->
{% extends "layout/base.html" %}
{% load humanize %}
{% block head %}
    {% include "layout/head.html" %}
{% endblock %}
{% block navi %}
    {% include "layout/navbar.html" %}
{% endblock navi %}
{% block header %}
    <div class="d-flex flex-column vh-100 justify-content-between">
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">장바구니</h1>
                    <p class="lead fw-normal text-white-50 mb-0">장바구니 summary</p>
                </div>
            </div>
        </header>
    {% endblock header %}
    {% block content %}
        <div class="container">
            {% if cart %}
                {% comment %} item = {"quantity":7,"price":3000.00,"product": <Product : 상품1>, "total_price":21000 } {% endcomment %}
                {% for item in cart %}
                    <div class="card mt-3">
                        <div class="row g-0">
                            <div class="col-md-4">
                                <img src=" {{ item.product.image.url }}"
                                     style="width:100%;
                                            height:25rem;
                                            object-fit:fill"
                                     class="img-fluid rounded-start"
                                     alt="..." />
                            </div>
                            <div class="col-md-8">
                                <div class="card-body mt-4">
                                    <center>
                                        <h5 class="card-title">{{ item.product.name }}</h5>
                                        <p class="card-text">{{ item.product.description }}</p>
                                        {% if item.product.is_sale %}
                                            {% comment %} <div class="d-flex justify-content-center small text-warning mb-2">
                          <div class="bi-star-fill"></div>
                          <div class="bi-star-fill"></div>
                          <div class="bi-star-fill"></div>
                          <div class="bi-star-fill"></div>
                          <div class="bi-star-fill"></div>
                        </div>
                        <!-- Product price-->
                        <strike>
                          ${{ product.price }}
                        </strike>
                        <br />
                        ID :&nbsp;{{ product.id }}
                        <br />
                                            &nbsp;${{ product.sale_price }} {% endcomment %}
                                            ${{ item.product.sale_price }}
                                            <br />
                                            ID :
                                            {{ item.product.id }}
                                        {% else %}
                                            ${{ item.product.price }}
                                            <br />
                                            ID :
                                            {{ item.product.id }}
                                        {% endif %}
                                        <br />
                                        <br />
                                        <div class="row justify-content-center">
                                            <div class="col-md-2">Quantity</div>
                                            <input type="text" value="{{ item.quantity }}" class="col-md-2">
                                        </div>
                                        <br />
                                        <a href="{% url 'store:home' %}" class="btn btn-secondary">홈으로</a>
                                        {% comment %} <button type="button"
         value="{{product.id}}"
         id="add-cart"
         class="btn btn-secondary">Add to Cart</button> {% endcomment %}
                                        <button type="button"
                                                data-index="{{ item.product.id }}"
                                                class="btn btn-secondary update-cart">업데이트</button>
                                        <button type="button"
                                                data-index="{{ item.product.id }}"
                                                class="btn btn-danger delete-product">삭제</button>
                                    </center>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <h1>장바구니에 물품이 없습니다.</h1>
            {% endif %}
        </div>
    {% endblock content %}
    {% block footer %}
        {% include "layout/footer.html" %}
    </div>
{% endblock footer %}
<!--dev_19-->
{% block script %}
    <script>
    $(document).on('click','.delete-product',function(e){
        $.ajax({
            type:"post",
            url:"{% url 'cart:delete_cart' %}",
            data:{
                product_id: $(this).data("index"),
                csrfmiddlewaretoken:'{{ csrf_token }}',
                action:"post"
            },
            success:function(json){
                console.log(json)
                location.reload();                 
            },
            error: function(e){
                console.log(e)
            }
        });
    });
    </script>
{% endblock script %}