cart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from cart import views

# dev_15
app_name = "cart"

urlpatterns = [
    path("add/", views.add_cart, name="add_cart"),
    path("", views.summary_cart, name="summary_cart"),  # dev_18
    path("delete/", views.delete_cart, name="delete_cart"),  # dev_19
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls")),  # dev_1
    path("accounts/", include("accounts.urls")),  # dev_9
    path("cart/", include("cart.urls")),  # dev_15
]

# dev_2
# http://127.0.0.1:8000/media/파일경로
# MEDIA_URL = "media/"  # ex) /media/photo1.png
# MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# dev_2
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

# dev_8
app_name = "store"

# dev_1
urlpatterns = [
    path("", views.home, name="home"),
    path("about", views.about, name="about"),  # dev_8 어바웃 페이지 추가
    path("product/<int:product_id>", views.product, name="product"),  # dev_13 제품상세
    path(
        "category_summary", views.category_summary, name="category_summary"
    ),  # dev_14 카테고리 처리
    path(
        "category/<int:category_id>", views.category, name="category"
    ),  # dev_14 카테고리 처리
]

store/models.py
from django.db import models


# Create your models here.
# dev_3
class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(default=0, max_digits=10, decimal_places=2)  # 9999999
    description = models.CharField(max_length=250, default="", blank=True, null=True)
    image = models.ImageField(upload_to="upload/product")
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    # dev_6
    is_sale = models.BooleanField(default=False)
    sale_price = models.IntegerField(default=0)

    def __str__(self):
        return self.name

store/views.py
from django.http import HttpResponse

from store.models import Product, Category
from django.shortcuts import redirect, render
from django.contrib import messages


# Create your views here.
# dev_1
# dev_5
def home(request):
    products = Product.objects.all()
    return render(request, "store/home.html", {"products": products})


# dev_8
def about(request):
    return render(request, "store/about.html", {})


# dev_13
def product(request, product_id):
    product = Product.objects.get(id=product_id)
    return render(request, "store/product.html", {"product": product})


# dev_14
def category_summary(request):
    categories = Category.objects.all()
    return render(request, "store/category_summary.html", {"categories": categories})


# dev_14
def category(request, category_id):

    try:
        category = Category.objects.get(id=category_id)
        # category = Category.objects.filter(id=category_id) #query_set

        # select * from product , category where product.category_id =  category.id
        # category = models.ForeignKey(Category, on_delete=models.CASCADE)
        products = Product.objects.filter(category=category)

        context = {
            "category": category,
            "products": products,
        }
        return render(request, "store/cotegory.html", context)

    except:
        messages.success(request, ("카테고리가 존재 하지 않습니다."))
        return redirect("store:home")

templates/store/about.html
{% extends "layout/base.html" %}
{% load humanize %}
{% block head %}
    {% include "layout/head.html" %}
{% endblock %}
{% block navi %}
    {% include "layout/navbar.html" %}
{% endblock navi %}
{% block header %}
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">About us...</h1>
                <p class="lead fw-normal text-white-50 mb-0">쇼핑몰 소개 페이지입니다.</p>
            </div>
        </div>
    </header>
{% endblock header %}
{% block content %}
    <div class="container">
        <div class="row">
            <center>
                <div class="col-8 mt-5">
                    <p>
                        대통령의 임기는 5년으로 하며, 중임할 수 없다. 헌법재판소의 조직과 운영 기타 필요한 사항은 법률로 정한다. 언론·출판에 대한 허가나 검열과 집회·결사에 대한 허가는 인정되지 아니한다.
                        모든 국민은 행위시의 법률에 의하여 범죄를 구성하지 아니하는 행위로 소추되지 아니하며, 동일한 범죄에 대하여 거듭 처벌받지 아니한다. 대통령의 임기가 만료되는 때에는 임기만료 70일 내지 40일전에 후임자를 선거한다.
                        정당의 목적이나 활동이 민주적 기본질서에 위배될 때에는 정부는 헌법재판소에 그 해산을 제소할 수 있고, 정당은 헌법재판소의 심판에 의하여 해산된다.
                        모든 국민은 학문과 예술의 자유를 가진다. 여자의 근로는 특별한 보호를 받으며, 고용·임금 및 근로조건에 있어서 부당한 차별을 받지 아니한다. 국회의원은 국회에서 직무상 행한 발언과 표결에 관하여 국회외에서 책임을 지지 아니한다.
                        재판의 심리와 판결은 공개한다. 다만, 심리는 국가의 안전보장 또는 안녕질서를 방해하거나 선량한 풍속을 해할 염려가 있을 때에는 법원의 결정으로 공개하지 아니할 수 있다.
                        국가는 주택개발정책등을 통하여 모든 국민이 쾌적한 주거생활을 할 수 있도록 노력하여야 한다. 새로운 회계연도가 개시될 때까지 예산안이 의결되지 못한 때에는 정부는 국회에서 예산안이 의결될 때까지 다음의 목적을 위한 경비는 전년도 예산에 준하여 집행할 수 있다.
                        지방자치단체는 주민의 복리에 관한 사무를 처리하고 재산을 관리하며, 법령의 범위안에서 자치에 관한 규정을 제정할 수 있다. 탄핵소추의 의결을 받은 자는 탄핵심판이 있을 때까지 그 권한행사가 정지된다.
                        의원을 제명하려면 국회재적의원 3분의 2 이상의 찬성이 있어야 한다. 대법원장의 임기는 6년으로 하며, 중임할 수 없다. 군사법원의 조직·권한 및 재판관의 자격은 법률로 정한다.
                    </p>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
            </center>
        </div>
    </div>
{% endblock content %}
{% block footer %}
    {% include "layout/footer.html" %}
{% endblock footer %}

templates/store/category_summary.html
{% extends "layout/base.html" %}
{% load humanize %}
{% block head %}
    {% include "layout/head.html" %}
{% endblock %}
{% block navi %}
    {% include "layout/navbar.html" %}
    <div class="d-flex flex-column vh-100 justify-content-between">
    {% endblock navi %}
    {% block header %}
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">카테고리</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Choose your Category Below..</p>
                </div>
            </div>
        </header>
    {% endblock header %}
    {% block content %}
        <div class="container">
            <div class="row">
                <center>
                    <div class="col-8 mt-5">
                        {% for category  in categories %}
                            <h3>
                                <a href="{% url 'store:category' category.id %}">{{ category.name }}</a>
                            </h3>
                        {% endfor %}
                    </div>
                </center>
            </div>
        </div>
    {% endblock content %}
    {% block footer %}
        {% include "layout/footer.html" %}
    </div>
{% endblock footer %}

templates/store/cotegory.html
<!--dev_14-->
{% extends "layout/base.html" %}
{% load humanize %}
{% block head %}
    {% include "layout/head.html" %}
{% endblock %}
{% block navi %}
    {% include "layout/navbar.html" %}
    <div class="d-flex flex-column vh-100 justify-content-between">
    {% endblock navi %}
    {% block header %}
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">{{ category.name }}</h1>
                    <p class="lead fw-normal text-white-50 mb-0">카테고리 페이지</p>
                </div>
            </div>
        </header>
    {% endblock header %}
    {% block content %}
        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    <!--dev_5 상품나오게 하기-->
                    {% for product  in products %}
                        <div class="col mb-5">
                            <div class="card h-100">
                                <!--dev_6 세일뱃지 처리-->
                                {% if product.is_sale %}
                                    <!-- Sale badge-->
                                    <div class="badge bg-dark text-white position-absolute"
                                         style="top: 0.5rem;
                                                right: 0.5rem">Sale</div>
                                {% endif %}
                                <!-- Product image-->
                                <img class="card-img-top"
                                     style="height:15rem;
                                            object-fit:cover"
                                     src="{{ product.image.url }}"
                                     alt="..." />
                                <!-- Product details-->
                                <div class="card-body p-4">
                                    <div class="text-center">
                                        <!-- Product name-->
                                        <h5 class="fw-bolder">{{ product.name }}</h5>
                                        <!-- Product reviews-->
                                        <div class="d-flex justify-content-center small text-warning mb-2">
                                            <div class="bi-star-fill"></div>
                                            <div class="bi-star-fill"></div>
                                            <div class="bi-star-fill"></div>
                                            <div class="bi-star-fill"></div>
                                            <div class="bi-star-fill"></div>
                                        </div>
                                        <!--dev_6 Product price-->
                                        {% if product.is_sale %}
                                            <span class="text-muted text-decoration-line-through">{{ product.price|floatformat:0|intcomma }}원</span>
                                            {{ product.sale_price|floatformat:0|intcomma }}원
                                        {% else %}
                                            {{ product.price|floatformat:0|intcomma }}원
                                        {% endif %}
                                    </div>
                                </div>
                                <!-- Product actions-->
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center">
                                        <!--dev_13-->
                                        <a class="btn btn-outline-dark mt-auto"
                                           href="{% url 'store:product' product.id %}">제품상세</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    {% endblock content %}
    {% block footer %}
        {% include "layout/footer.html" %}
        <div>
        {% endblock footer %}

templates/store/home-backup.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Shop Homepage - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon"
              type="image/x-icon"
              href="{% static 'store/assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
              rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'store/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!">Start Bootstrap</a>
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#!">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#!">About</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle"
                               id="navbarDropdown"
                               href="#"
                               role="button"
                               data-bs-toggle="dropdown"
                               aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" href="#!">All Products</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider" />
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#!">Popular Items</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#!">New Arrivals</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                        </button>
                    </form>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Shop in style</h1>
                    <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
                </div>
            </div>
        </header>
        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    <!--dev_5 상품나오게 하기-->
                    {% for product  in products %}
                        <div class="col mb-5">
                            <div class="card h-100">
                                <!--dev_6 세일뱃지 처리-->
                                {% if product.is_sale %}
                                    <!-- Sale badge-->
                                    <div class="badge bg-dark text-white position-absolute"
                                         style="top: 0.5rem;
                                                right: 0.5rem">Sale</div>
                                {% endif %}
                                <!-- Product image-->
                                <img class="card-img-top"
                                     style="height:15rem;
                                            object-fit:cover"
                                     src="{{ product.image.url }}"
                                     alt="..." />
                                <!-- Product details-->
                                <div class="card-body p-4">
                                    <div class="text-center">
                                        <!-- Product name-->
                                        <h5 class="fw-bolder">{{ product.name }}</h5>
                                        <!-- Product reviews-->
                                        <div class="d-flex justify-content-center small text-warning mb-2">
                                            <div class="bi-star-fill"></div>
                                            <div class="bi-star-fill"></div>
                                            <div class="bi-star-fill"></div>
                                            <div class="bi-star-fill"></div>
                                            <div class="bi-star-fill"></div>
                                        </div>
                                        <!--dev_6 Product price-->
                                        {% if product.is_sale %}
                                            <span class="text-muted text-decoration-line-through">{{ product.price|floatformat:0|intcomma }}원</span>
                                            {{ product.sale_price|floatformat:0|intcomma }}원
                                        {% else %}
                                            {{ product.price|floatformat:0|intcomma }}원
                                        {% endif %}
                                    </div>
                                </div>
                                <!-- Product actions-->
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center">
                                        <a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container">
                <p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'store/js/scripts.js' %}"></script>
    </body>
</html>

templates/store/home.html
{% extends "layout/base.html" %}
{% load humanize %}
{% block head %}
    {% include "layout/head.html" %}
{% endblock %}
{% block navi %}
    {% include "layout/navbar.html" %}
{% endblock navi %}
{% block header %}
    {% include "layout/header.html" %}
{% endblock header %}
{% block content %}
    <!-- Section-->
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                <!--dev_5 상품나오게 하기-->
                {% for product  in products %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!--dev_6 세일뱃지 처리-->
                            {% if product.is_sale %}
                                <!-- Sale badge-->
                                <div class="badge bg-dark text-white position-absolute"
                                     style="top: 0.5rem;
                                            right: 0.5rem">Sale</div>
                            {% endif %}
                            <!-- Product image-->
                            <img class="card-img-top"
                                 style="height:15rem;
                                        object-fit:cover"
                                 src="{{ product.image.url }}"
                                 alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ product.name }}</h5>
                                    <!-- Product reviews-->
                                    <div class="d-flex justify-content-center small text-warning mb-2">
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                    </div>
                                    <!--dev_6 Product price-->
                                    {% if product.is_sale %}
                                        <span class="text-muted text-decoration-line-through">{{ product.price|floatformat:0|intcomma }}원</span>
                                        {{ product.sale_price|floatformat:0|intcomma }}원
                                    {% else %}
                                        {{ product.price|floatformat:0|intcomma }}원
                                    {% endif %}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center">
                                    <!--dev_13-->
                                    <a class="btn btn-outline-dark mt-auto"
                                       href="{% url 'store:product' product.id %}">제품상세</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock content %}
{% block footer %}
    {% include "layout/footer.html" %}
{% endblock footer %}

templates/store/product.html
<!--dev_13-->
{% extends "layout/base.html" %}
{% load humanize %}
{% block head %}
    {% include "layout/head.html" %}
{% endblock %}
{% block navi %}
    {% include "layout/navbar.html" %}
{% endblock navi %}
{% block content %}
    <section class="py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="row gx-4 gx-lg-5 align-items-center">
                <div class="col-md-6">
                    <img class="card-img-top mb-5 mb-md-0"
                         src="{{ product.image.url }}"
                         alt="...">
                </div>
                <div class="col-md-6">
                    <div class="small mb-1">SKU: {{ product.id }}</div>
                    <h1 class="display-5 fw-bolder">{{ product.name }}</h1>
                    <div class="fs-5 mb-5">
                        {% if product.is_sale %}
                            <span class="text-decoration-line-through">{{ product.price|floatformat:0|intcomma }}원</span>
                            <span>{{ product.price|floatformat:0|intcomma }}원</span>
                        {% else %}
                            {{ product.price|floatformat:0|intcomma }}원
                        {% endif %}
                    </div>
                    <p class="lead">{{ product.description }}</p>
                    <div class="d-flex">
                        <input class="form-control text-center me-3"
                               id="inputQuantity"
                               type="num"
                               value="1"
                               style="max-width: 3rem">
                        <!--dev_15-->
                        <button class="btn btn-outline-dark flex-shrink-0"
                                type="button"
                                value="{{ product.id }}"
                                id="add-cart">
                            <i class="bi-cart-fill me-1"></i>
                            <!--dev_15-->
                            Add to cart(장바구니 담기)
                        </button>
                    </div>
                    <br>
                    <a class="btn btn-secondary" href="{% url 'store:home' %}">홈으로</a>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}
{% block footer %}
    {% include "layout/footer.html" %}
{% endblock footer %}
<!--dev_15-->
{% block script %}
    <script>
    $(document).on('click','#add-cart',function(e){
        $.ajax({
            type:"post",
            url:"{% url 'cart:add_cart' %}",
            data:{
                product_id:$("#add-cart").val(),
                product_qty: $("#inputQuantity").val(),
                csrfmiddlewaretoken:'{{ csrf_token }}',
                action:"post"
            },
            success:function(json){
                console.log(json)
                //dev_16
                $('#cart_quantity').text(json.qty)
                //dev_17
                //location.reload();                 
            },
            error: function(e){
                console.log(e)
            }
        });
    });
    </script>
{% endblock %}